version: '3.8'

services:
  backend:
    image: honeybee-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: honeybee_backend
    ports:
      - "${BACKEND_HTTP}:8081"
    environment:
      NODE_ENV: production
      BACKEND_HTTP: 8081
      MONGODB_URI: "${MONGODB_URI}"
      SECRET_KEY: "${SECRET_KEY}"
    env_file:
      - .env
    volumes:
      - node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  node_modules: