version: "3.8"

services:
    mongo:
        image: mongo:6
        container_name: mongodb
        env_file:
            -   .env
        ports:
        - "27017:27017"
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    mongo-express:
        image: mongo-express
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}